name: Proto-Check-Correctness

on:
  push:
    branches:
      - main
    paths:
      - "api/proto/**"
  pull_request:
    paths:
      - "api/proto/**"

jobs:
  lint:
    name: buf-checks
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
      - uses: actions/checkout@v4

      - uses: bufbuild/buf-action@v1
        with:
          input: api/proto
          lint: true
          format: true
          breaking: false
          push: false
